### ISSUE TITLE
Minification can mess with calc() parameters

### ISSUE THREAD

**Issue by kotmapchly** [jleeson/rollup-plugin-import-css#33]
If minification is applied to already minified (or partially minified) CSS, it may broke calc() parameters, changing them from:
`calc(x + y)`
to:
`calc(x+ y)`

According to spec, the + and - operators must be surrounded by whitespace.

This partial rule may catch space between first argument and +/- sign:
`\s+([+-])(?=.*\{)`

Additionally 'exclude' option doesn't match the description: 'files to exclude when minifying'. Instead it disables whole transformation process.

**Comment by jleeson** [comment]
Thanks for bringing this to my attention, can you provide some example css where this is breaking? The current regex should be ignoring whitespace inside parenthesis, but its possible there is some match ahead of it which is resulting in different behavior.

I have updated the README to correctly describe the include/exclude plugin options.

**Comment by kotmapchly** [comment]
I have some mixed CSS (minified and unminified) - this bug appears for minified one-liners, between `calc()` and `{` of the next rule, for example:
https://regex101.com/r/Gv0eU0/1

I temporary fixed it by expanding regex in plugin - adding rule for `calc()` in similar fashion like rules for `"..."` and `'...'`. It doesn't solve nested `calc()`'s, but is enough for me.

**Comment by jleeson** [comment]
that helps, thank you!

**Comment by jleeson** [comment]
v3.5.8 of this plugin, now explicitly excludes calc from its minification process and is now correctly working with your example. I have also added a note to the readme that you can bring your own css minifier and use it via the transform function for cases where the simple regex minifer may not work temporarily.

Let me know if you run into any more problems!

**Comment by kotmapchly** [comment]
Yes, it works. Thank You.
